server:
  port: 8091
  
spring:
  boot:
    admin:
      client:
        url: http://localhost:8091
        enabled: true
  application:
    name: Admin Server
  main:
    allow-bean-definition-overriding: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /admin
  endpoint:
    health:
      show-details: always

security:
  oauth2:
    client:
#      grantType: authorization_code
      accessTokenUri: http://localhost:8090/oauth/token
      userAuthorizationUri: http://localhost:8090/oauth/authorize
      clientId: clientABC
      clientSecret: secretXYZ
    resource:
      user-info-uri: http://localhost:8090/user
      token-info-uri: http://localhost:8090/oauth/check_token
      preferTokenInfo: true
      filter-order: 3
  basic:
    enabled: false

logging:
  file: ../logs/AdminServer.log 
  level: 
    org.springframework: INFO
    de.codecentric: INFO
  pattern: 
      file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"