server:
  port: 8090
  
logging:
  file: /logs/AuthourizationServer.log 
  level: 
    org.springframework: DEBUG
  pattern: 
      file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
security:
  basic:
    enabled: false
