server:
  port: 8090
  
security:
  basic:
    enabled: false

spring:
  boot:
    admin:
      client:
        url: http://localhost:8091
        enabled: false
  application:
    name: Authorization Server

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /admin
  
logging:
  file: /logs/AuthourizationServer.log 
  level: 
    org.springframework: DEBUG
  pattern: 
      file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
